"""Create initial tables

Revision ID: 03e68f36c735
Revises: 
Create Date: 2024-12-10 08:32:12.851663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e68f36c735'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('coverage_pages', sa.JSON(), nullable=False),
    sa.Column('primary_topics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('context_pages', sa.JSON(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('cognitive_level', sa.Enum('KNOWLEDGE', 'COMPREHENSION', 'APPLICATION', 'ANALYSIS', 'SYNTHESIS', 'EVALUATION', name='cognitivelevel'), nullable=False),
    sa.Column('key_concepts', sa.JSON(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('model_answer', sa.JSON(), nullable=False),
    sa.Column('grading_criteria', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('metadata')
    # ### end Alembic commands ###
